SELECT a.AUTHOR_ID
, b.AUTHOR_NAME
, a.CATEGORY
, (SUM(c.SALES * a.PRICE)) AS TOTAL_SALES
FROM BOOK a
JOIN AUTHOR b ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES c ON a.BOOK_ID = c.BOOK_ID
WHERE c.SALES_DATE LIKE "2022-01%"
GROUP BY 1,3
ORDER BY 1 ASC,  3 DESC