# SELECT CART_ID
# FROM CART_PRODUCTS
# WHERE CART_ID = (
# SELECT CART_ID
# FROM CART_PRODUCTS


SELECT a.CART_ID
FROM CART_PRODUCTS a
JOIN (SELECT CART_ID
     FROM CART_PRODUCTS
     WHERE NAME = "Yogurt") b
ON a.CART_ID = b.CART_ID
WHERE a.NAME = "Milk"
