-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.PARENT_ITEM_ID IS NULL
GROUP BY A.ITEM_ID
ORDER BY A.ITEM_ID DESC;

# SELECT *
# FROM ITEM_TREE