SELECT b.USER_ID
, b.NICKNAME
, CONCAT(b.CITY,' ', b.STREET_ADDRESS1,' ',b.STREET_ADDRESS2) AS 전체주소
, CONCAT(SUBSTRING(b.TLNO, 1, 3), '-', SUBSTRING(b.TLNO, 4, 4), '-', SUBSTRING(b.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER  b
WHERE b.USER_ID IN (
    SELECT a.WRITER_ID
    FROM USED_GOODS_BOARD a
    GROUP BY a.WRITER_ID
    HAVING COUNT(a.WRITER_ID) >= 3
)
ORDER BY b.USER_ID DESC;
