SELECT YEAR(b.SALES_DATE) AS YEAR
, MONTH(b.SALES_DATE) AS MONTH
, a.GENDER
, COUNT(DISTINCT a.USER_ID) AS USERS
FROM USER_INFO a
JOIN ONLINE_SALE b ON a.USER_ID = b.USER_ID
WHERE a.GENDER IS NOT NULL
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER
ORDER BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER ASC
