WITH MEMBER AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
) # 2021년 가입한 회원 

SELECT YEAR(SALES_DATE) AS YEAR,
       MONTH(SALES_DATE) AS MONTH,
       COUNT(DISTINCT(USER_ID)) AS PUCHASED_USERS,
       ROUND((COUNT(DISTINCT(USER_ID)) / (SELECT COUNT(USER_ID) FROM MEMBER)),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                  FROM MEMBER)
GROUP BY YEAR , MONTH
ORDER BY YEAR , MONTH