WITH RECURSIVE CTE AS (
    SELECT
        ID, 1 AS GENERATION
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
    UNION ALL
    SELECT
        A.ID, GENERATION + 1 AS GENERATION
    FROM
        ECOLI_DATA A LEFT JOIN CTE B ON A.PARENT_ID = B.ID
    WHERE
        A.PARENT_ID = B.ID
)
SELECT COUNT(*) COUNT, GENERATION FROM CTE AS A
WHERE NOT EXISTS(SELECT 1 FROM ECOLI_DATA WHERE PARENT_ID = A.ID)
GROUP BY GENERATION
