SELECT A.HISTORY_ID, ROUND(A.DAILY_FEE * (1-COALESCE(B.DISCOUNT_RATE/100,0)) * A.DURATION, 0) AS FEE
FROM(
    # '트럭'의 대여 기록 정보
    SELECT A.HISTORY_ID, A.CAR_ID, DATEDIFF(A.END_DATE, A.START_DATE)+1 AS DURATION,
       B.CAR_TYPE, B.DAILY_FEE,
       CASE WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE '할인 없음'
            END AS 'DURATION_TYPE'
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    LEFT JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
    ) AS A
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
           ON (A.DURATION_TYPE = B.DURATION_TYPE) AND (A.CAR_TYPE = B.CAR_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC