# SELECT K.HISTORY_ID, CASE
#                         WHEN K.RENTAL_DATE >= 90 THEN FLOOR(K.DAILY_FEE * 0.9 * K.RENTAL_DATE)
#                         WHEN K.RENTAL_DATE >= 30 THEN FLOOR(K.DAILY_FEE * 0.93 * K.RENTAL_DATE)
#                         WHEN K.RENTAL_DATE >=7 THEN FLOOR(K.DAILY_FEE * 0.95 * K.RENTAL_DATE)
#                     ELSE K.DAILY_FEE * K.RENTAL_DATE
#                     END AS FEE
# FROM
#     (
#         SELECT B.HISTORY_ID, A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, 
#             ( B.END_DATE - B.START_DATE + 1) AS RENTAL_DATE
#         FROM CAR_RENTAL_COMPANY_CAR A 
#         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
#         WHERE A.CAR_TYPE = "트럭"
#     ) AS K
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T ON K.CAR_TYPE = T.CAR_TYPE
# GROUP BY K.HISTORY_ID
# ORDER BY FEE DESC, K.HISTORY_ID DESC;


SELECT 
    R.HISTORY_ID, 
    FLOOR(C.DAILY_FEE * (DATEDIFF(R.END_DATE, R.START_DATE) + 1) * (1 - IFNULL(D.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY R ON C.CAR_ID = R.CAR_ID
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
        AND (
            (DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 90 AND D.DURATION_TYPE = '90일 이상') OR
            (DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 30 AND DATEDIFF(R.END_DATE, R.START_DATE) + 1 < 90 AND D.DURATION_TYPE = '30일 이상') OR
            (DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 7 AND DATEDIFF(R.END_DATE, R.START_DATE) + 1 < 30 AND D.DURATION_TYPE = '7일 이상')
        )
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    R.HISTORY_ID DESC;
