SELECT 
    RH.HISTORY_ID,
    FLOOR(
        CC.DAILY_FEE * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) * 
        (
            CASE
                WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 90 THEN 1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = CC.CAR_TYPE AND DURATION_TYPE = '90일 이상') / 100
                WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30 THEN 1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = CC.CAR_TYPE AND DURATION_TYPE = '30일 이상') / 100
                WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 7 THEN 1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = CC.CAR_TYPE AND DURATION_TYPE = '7일 이상') / 100
                ELSE 1
            END
        )
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR CC
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON CC.CAR_ID = RH.CAR_ID
WHERE 
    CC.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    RH.HISTORY_ID DESC;
