SELECT c.APNT_NO
, a.PT_NAME
, a.PT_NO
, b.MCDP_CD
, b.DR_NAME
, c.APNT_YMD
FROM  APPOINTMENT C
JOIN PATIENT A  ON a.PT_NO = c.PT_NO
JOIN DOCTOR b ON b.DR_ID = c.MDDR_ID
WHERE c.APNT_YMD LIKE "2022-04-13%"
AND c.APNT_CNCL_YN = "N"
AND c.MCDP_CD = "CS"
ORDER BY c.APNT_YMD ASC