# SELECT HOUR(A.DATETIME) AS HOUR, COUNT(*) AS COUNT
# FROM ANIMAL_OUTS A
# LEFT JOIN ANIMAL_OUTS B ON A.DATETIME = B.DATETIME
# GROUP BY 1
# ORDER BY 1 

WITH RECURSIVE hours AS (
  SELECT 0 AS hour
  UNION ALL
  SELECT hour + 1 FROM hours WHERE hour < 23
)
SELECT 
  h.hour,
  COUNT(a.ANIMAL_ID) AS count
FROM 
  hours h
LEFT JOIN 
  ANIMAL_OUTS a ON h.hour = HOUR(a.DATETIME)
GROUP BY 
  h.hour
ORDER BY 
  h.hour;
