SELECT b.USER_ID, b.NICKNAME, sum(a.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_USER b ON a.WRITER_ID = b.USER_ID
WHERE a.STATUS = "DONE"
GROUP BY a.WRITER_ID
having TOTAL_SALES >= 700000
order by TOTAL_SALES asc
