-- 코드를 입력하세요
# SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
# FROM (
#     SELECT CAR_ID, START_DATE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE >= "2022-08-01" AND START_DATE <= "2022-10-31"
#     GROUP BY 1
#     HAVING COUNT(*) >= 5
#     ) A
# GROUP BY 1, 2
# ORDER BY 1 ASC, 2 DESC

# SELECT  MONTH(START_DATE), CAR_ID, COUNT(CAR_ID)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= "2022-08-01" AND START_DATE <= "2022-10-31"
# GROUP BY 1, 2
# HAVING COUNT(CAR_ID) >= 5
# ORDER BY 1 ASC, 2 DESC

SELECT 
    EXTRACT(MONTH FROM START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID IN (
        SELECT 
            CAR_ID
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE 
            START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY 
            CAR_ID
        HAVING 
            COUNT(*) >= 5
    )
GROUP BY 
    EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY 
    EXTRACT(MONTH FROM START_DATE) ASC, CAR_ID DESC;