SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE (FISH_NAME, LENGTH) 
IN (
    SELECT FISH_NAME, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY I.FISH_TYPE, FISH_NAME
)