# WITH A AS (
# SELECT FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG(LENGTH) >= 33
#     )
# SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, I.FISH_TYPE
# FROM FISH_INFO I
# INNER JOIN A ON I.FISH_TYPE = A.FISH_TYPE
# GROUP BY I.FISH_TYPE
# ORDER BY I.FISH_TYPE ASC

SELECT 
    COUNT(*) AS FISH_COUNT, 
    MAX(COALESCE(LENGTH, 10)) AS MAX_LENGTH, 
    FISH_TYPE
FROM 
    FISH_INFO
GROUP BY 
    FISH_TYPE
HAVING 
    AVG(COALESCE(LENGTH, 10)) >= 33
ORDER BY 
    FISH_TYPE ASC;
